openapi: 3.0.0
info:
  title: News Site
  version: '1.0'
  description: News Site Backend
  contact:
    name: Henrik Kurkela
    url: www.github.com/henrikkurkela
servers:
  - url: 'http://localhost:3001'
    description: Local Server
paths:
  /api/users:
    parameters: []
    get:
      summary: Get User Info
      tags:
        - news
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    email:
                      type: string
                      minLength: 1
                    username:
                      type: string
                      minLength: 1
                    avatar:
                      type: string
                      minLength: 1
                    type:
                      type: string
                      minLength: 1
                    createdAt:
                      type: string
                      minLength: 1
                    updatedAt:
                      type: string
                      minLength: 1
                  required:
                    - id
                    - email
                    - username
                    - avatar
                    - type
                    - createdAt
                    - updatedAt
              examples: {}
      operationId: get-users-userId
      description: Get all user's information.
  /api/news:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - category
                    - headline
                    - likes
                    - content
                    - createdAt
                    - updatedAt
                    - userId
                  properties:
                    id:
                      type: number
                    category:
                      type: number
                    headline:
                      type: string
                      minLength: 1
                    likes:
                      type: number
                    content:
                      type: string
                      minLength: 1
                    createdAt:
                      type: string
                      minLength: 1
                    updatedAt:
                      type: string
                      minLength: 1
                    userId:
                      type: number
      operationId: get-api-news
      description: Get all news articles.
    parameters: []
  /api/comments:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - content
                    - createdAt
                    - updatedAt
                    - newsId
                  properties:
                    id:
                      type: number
                    content:
                      type: string
                      minLength: 1
                    createdAt:
                      type: string
                      minLength: 1
                    updatedAt:
                      type: string
                      minLength: 1
                    userId: {}
                    newsId:
                      type: number
      operationId: get-api-comments
      description: Get all comments for all articles.
    parameters: []
  /api/market:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - x
                    - 'y'
                  properties:
                    x:
                      type: number
                    'y':
                      type: number
      operationId: get-api-market
      description: Get current market status. Used for business news section Market Tracker.
    parameters: []
  /api/ads:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - picture
                    - href
                    - createdAt
                    - updatedAt
                  properties:
                    id:
                      type: number
                    picture:
                      type: string
                      minLength: 1
                    href:
                      type: string
                      minLength: 1
                    createdAt:
                      type: string
                      minLength: 1
                    updatedAt:
                      type: string
                      minLength: 1
      operationId: get-api-ads
      description: Get all advertisements.
    parameters: []
components:
  schemas: {}
tags:
  - name: news
